name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - index.html  # Trigger only when index.html changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional if you're using a static site generator)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (if you have a package.json)
      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Step 4: Build the site (if you have a build step)
      - name: Build the site
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory to publish; update if your build generates files in a specific folder
